# Generated by Django 5.0.1 on 2024-05-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_question',
            name='answer_key',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
