# Generated by Django 5.0.1 on 2024-05-11 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_tbl_test_question_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_test_question',
            name='test_question_answer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
